version: "3.9"

services:
  app:
    restart: always
    build:
      dockerfile: Dockerfile
      target: alpine
      context: .
    volumes:
      - .:/workspace:cached
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
