version: "3.9"

services:
  app:
    restart: always
    build:
      dockerfile: Dockerfile
      target: alpine
      context: .
    volumes:
      - .:/workspace:cached
    environment:
      - VIRTUAL_HOST=devweb.app
      - LETSENCRYPT_HOST=devweb.app
