version: "3.9"

services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /usr/share/nginx/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/certs/:/etc/nginx/certs/
      - ./nginx/dhparam/:/etc/nginx/dhparam/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/vhost.d/:/etc/nginx/vhost.d/

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - ./acme.sh/:/etc/acme.sh/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy

  app:
    restart: always
    build:
      dockerfile: Dockerfile
      target: alpine
      context: .
    volumes:
      - .:/workspace:cached
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - PORT=${PORT}
