version: '2'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
    environment:
      - GOPATH=/go/src/app
      - VIRTUAL_HOST=experimentalcommunity.org
      - LETSENCRYPT_HOST=experimentalcommunity.org