version: "3.9"

services:
  gocd:
    depends_on:
      - db
    image: gocd/gocd-server:v21.2.0
    volumes:
      - ./gocd/server:/godata
    environment:
      - VIRTUAL_HOST=${GOCD_SERVER_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${GOCD_SERVER_LETSENCRYPT_HOST}
    ports:
      - "${GOCD_SERVER_PORT}:${GOCD_SERVER_PORT}"

  agent:
    depends_on:
      - gocd
      - db
    image: gocd/gocd-agent-docker-dind:v21.2.0
    restart: always
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gocd/agent/:/godata
    environment:
      - GO_SERVER_URL=http://gocd:${GOCD_SERVER_PORT}/go

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_VIRTUAL_PORT}:${POSTGRES_VIRTUAL_PORT}"

volumes:
  postgresql:
  postgresql_data:
   