version: "3.9"

services:
  jenkins:
    build:
      dockerfile: jenkins.Dockerfile
      context: ./
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
    environment:
      - VIRTUAL_HOST=${JENKINS_VIRTUAL_HOST}
      - VIRTUAL_PORT=${JENKINS_VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${JENKINS_LETSENCRYPT_HOST}
    ports:
      - "${JENKINS_VIRTUAL_PORT}:${JENKINS_VIRTUAL_PORT}"
      - "${JENKINS_AGENT_VIRTUAL_PORT}:${JENKINS_AGENT_VIRTUAL_PORT}"

volumes:
    client-certs:
